import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Providers } from '../provider'

import FirstHeader from '@/components/layout/FirstHeader.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BNKLUB',
  description: 'Generated by BNK System Group 3',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <FirstHeader />
        {children}
        </Providers>
      </body>
    </html>
  )
}
